kind: pipeline
name: default

steps:
- name: extract 
  image: buildkite/puppeteer:v3.0.4
  environment:
    ROAM_USERNAME:
      from_secret: ROAM_USERNAME
    ROAM_PASSWORD:
      from_secret: ROAM_PASSWORD
    ROAM_DATABASE:
      from_secret: ROAM_DATABASE
  commands:
  - node export/index.js

- name: transform
  image: python:3.8-alpine
  commands:
  - mkdir zip
  - mkdir posts
  - cp *.zip ./zip
  - cd ./zip;
  - unzip *.zip;
  - pwd
  - find . -name \*.md -exec python3 ../transform/blog.py -i {} -o ../posts/ \;
  - ls ../posts/*
- name: blog
  image: bitnami/git
  environment:
    SSH_KEY:
      from_secret: ssh-key
    GIT_SSH_COMMAND: ssh -i /drone/src/key -v
  commands:
  - echo "$SSH_KEY" > key
  - ls -la *
  - chmod 600 key
  - ls posts/*
  - mkdir ~/.ssh
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - rm -rf blog/
  - git clone git@github.com:kozko2001/blog-hugo.git blog/
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - cp posts/* blog/content/posts/
  - git -C blog/ add .
  - git -C blog/ status
  - git -C blog/ commit -m "add content from roam-export"
  - git -C blog/ push
