kind: pipeline
name: default

steps:
- name: extract 
  image: buildkite/puppeteer:v3.0.4
  environment:
    ROAM_USERNAME:
      from_secret: ROAM_USERNAME
    ROAM_PASSWORD:
      from_secret: ROAM_PASSWORD
    ROAM_DATABASE:
      from_secret: ROAM_DATABASE
  commands:
  - node export/index.js

- name: transform
  image: python:3.8-alpine
  commands:
  - mkdir zip
  - mkdir posts
  - cp *.zip ./zip
  - cd ./zip;
  - unzip *.zip;
  - pwd
  - find . -name \*.md -exec python3 ../transform/blog.py -i {} > /tmp/test.md \; -exec cp /tmp/test.md ../posts/{} \;
  - ls ../posts/*
- name: blog
  image: alpine/git
  commands:
  - ls posts/*
  - git clone https://github.com/kozko2001/blog-hugo.git blog/
  - cp posts/* blog/content/posts/
  - mv -r . /tmp/
  - shopt -s dotglob; mv /tmp/blog/* .
  - git add .
  - git status
  - git commit -m "add content from roam-export"
  - git push
