# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 * * * *'
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    timeout-minutes: 10
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: export roam
      shell: bash
      env:
        ROAM_USERNAME: ${{ secrets.ROAM_USERNAME }}
        ROAM_PASSWORD: ${{ secrets.ROAM_PASSWORD }}
        ROAM_DATABASE: ${{ secrets.ROAM_DATABASE }}
      run: |
        mkdir zip
        cd export
        npm install
        npm install -g npx
        node index.js
        npx nunzip *.zip -d ../zip
        unzip -o  *.zip -d ../zip | true
        echo "I AM SUCCESSFUL?"
        ls ../zip/

    - name: transform to hugo markdown
      shell: bash
      run: |
         ls ./zip
