# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 * * * *'
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    timeout-minutes: 10
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: export roam
      shell: bash
      env:
        NEXT_CLOUD_HOST: ${{ secrets.NEXT_CLOUD_HOST }}
        NEXT_CLOUD_PASSWORD: ${{ secrets.NEXT_CLOUD_PASSWORD }}
        NEXT_CLOUD_USER: ${{ secrets.NEXT_CLOUD_USER }}
      run: |
        mkdir zip
        cd export
        pip install -r requirements.txt
        python main.py obsidian-notes/ data.zip
        unzip data.zip -d ../zip
        mv -f ../zip/obsidian-notes/* ../zip/
        rm -rf ../zip/obsidian-notes
        ls ../zip/*

    - name: get blog
      shell: bash
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      run: |
        git config --global user.email "kozko2001@gmail.com"
        git config --global user.name "kozko2001"
        git clone "https://$API_TOKEN_GITHUB@github.com/kozko2001/blog-hugo.git" "blog"

    - name: transform to hugo markdown
      shell: bash
      run: |
        pip3 install setuptools
        pip3 install -r transform/requirements.txt
        cd zip
        find . -name \*.md -exec python3 ../transform/blog.py -i {} -o ../blog/content/posts/obsidian/ -p ../blog/content/posts/obsidian/images \;
        mv images/* ../blog/content/posts/obsidian/images

    - name: transform roam to anki cards
      shell: bash
      env:
        ANKI_USERNAME: ${{ secrets.ANKI_USERNAME }}
        ANKI_PASSWORD: ${{ secrets.ANKI_PASSWORD }}
      run: |
        git clone https://github.com/kozko2001/roam-to-anki.git
        ls -la roam-to-anki/*
        pip3 install setuptools
        pip3 install -r roam-to-anki/importer/requirements.txt

        cd roam-to-anki/transform;
        npm install
        node index.js -i ../../zip -o ../decks.json
        cd ../importer
        python3 import.py --infile ../decks.json


    - name: push to my blog
      shell: bash
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      run: |
        ./commit.sh blog/
